#!/bin/bash
#
# basic puppet syntax check 
# 

for ppfile in `git diff --name-only HEAD~1 | grep "\.pp\|\.erb"` 
do
  if [[ -f $ppfile ]] 
  then
    case $ppfile in 
    *.pp)
      puppet parser validate $ppfile
      if [[ $? -ne 0 ]] 
      then
        echo "$ppfile not validated by puppet parser"
        puppet_syntax=1
      else
        echo "$ppfile has been validated by puppet parser"
      fi ;;
    *.erb)
      erb -P -x -T '-' "$ppfile" | ruby -c
      if [[ $? -ne 0 ]]
      then
        echo "$ppfile not a valid erb file"
        puppet_syntax=1
      else
        echo "$ppfile is a valid erb file"
      fi ;;
    esac
  fi
done

exit $puppet_syntax;
